apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webhook-pull-policy
  namespace: k8s-webhook-pull-policy
  labels:
    app: k8s-webhook-pull-policy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-webhook-pull-policy
  template:
    metadata:
      labels:
        app: k8s-webhook-pull-policy
    spec:
      containers:
        - name: k8s-webhook-pull-policy
          image: chaudhryfaisal/k8s-webhook-pull-policy:d46d40f
          imagePullPolicy: IfNotPresent
          args:
            - --debug
            - --tls-cert-file-path=/etc/webhook/certs/cert.pem
            - --tls-key-file-path=/etc/webhook/certs/key.pem
            - --webhook-image-pull-policy=IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            periodSeconds: 15
            httpGet:
              path: /healthz
              port: metrics
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: k8s-webhook-pull-policy-certs
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-webhook-pull-policy
  namespace: k8s-webhook-pull-policy
  labels:
    app: k8s-webhook-pull-policy
spec:
  ports:
  - name: http
    port: 443
    targetPort: 8080
  - name: metrics
    port: 8081
    targetPort: 8081
  selector:
    app: k8s-webhook-pull-policy
